before:
  hooks:
    - go mod tidy
builds:
  -
    id: pgsp-linux
    main: ./cmd/pgsp
    binary: pgsp
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
  -
    id: pgsp-other
    main: ./cmd/pgsp
    binary: pgsp
    ldflags:
      - -X github.com/noborus/pgsp/cmd.Version={{.Version}}
      - -X github.com/noborus/pgsp/cmd.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64

archives:
  -
    id: pgsp-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
    - pgsp-linux
    - pgsp-other
    format: zip

nfpms:
  -
    id: pgsp-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - pgsp-linux
    homepage: https://github.com/noborus/pgsp
    maintainer: Noboru Saito <noborusai@gmail.com>
    description: PostgreSQL Stat Progress CLI Monitor
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1

brews:
  -
    name: pgsp
    tap:
      owner: noborus
      name: homebrew-tap
    commit_author:
      name: noborus
      email: noborusai@gmail.com
    homepage: https://github.com/noborus/pgsp
    description: "PostgreSQL Stat Progress CLI Monitor"
    test:
      system "#{bin}/pgsp --version"
    install:
      bin.install "pgsp"
